// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDDsvgiS_CBnmQGsu3H2vF1W2yta7Nysc',
    appId: '1:459378732635:web:2e152859e16adfd872997e',
    messagingSenderId: '459378732635',
    projectId: 'robloxhackers-lol',
    authDomain: 'robloxhackers-lol.firebaseapp.com',
    storageBucket: 'robloxhackers-lol.appspot.com',
    measurementId: 'G-815TJX7480',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6xkmLUn_8pojHEP5-0fpwMYPTNUjp_jA',
    appId: '1:459378732635:android:1e591864ea3ba60072997e',
    messagingSenderId: '459378732635',
    projectId: 'robloxhackers-lol',
    storageBucket: 'robloxhackers-lol.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApWzCCECj1zRX4ffoKqqBMm_8fbUTsP_M',
    appId: '1:459378732635:ios:bfaee92eda840cbe72997e',
    messagingSenderId: '459378732635',
    projectId: 'robloxhackers-lol',
    storageBucket: 'robloxhackers-lol.appspot.com',
    iosBundleId: 'com.example.robloxhackers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApWzCCECj1zRX4ffoKqqBMm_8fbUTsP_M',
    appId: '1:459378732635:ios:bfaee92eda840cbe72997e',
    messagingSenderId: '459378732635',
    projectId: 'robloxhackers-lol',
    storageBucket: 'robloxhackers-lol.appspot.com',
    iosBundleId: 'com.example.robloxhackers',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDDsvgiS_CBnmQGsu3H2vF1W2yta7Nysc',
    appId: '1:459378732635:web:ef09183b9e78fccc72997e',
    messagingSenderId: '459378732635',
    projectId: 'robloxhackers-lol',
    authDomain: 'robloxhackers-lol.firebaseapp.com',
    storageBucket: 'robloxhackers-lol.appspot.com',
    measurementId: 'G-3KYM67QYYF',
  );
}
